const ImpactPage = () => (
  <div>
      {/* Hero Section */}
      <section className="section-padding pt-32 bg-surface">
        <div className="container-narrow">
          <div className="grid md:grid-cols-12 gap-12 items-center">
            <div className="md:col-span-7">
              <span className="inline-block px-4 py-1.5 rounded-full bg-secondary-container text-on-secondary-container text-xs font-bold tracking-wider mb-6">
                INSTITUTIONAL IMPACT
              </span>
              <h1 className="headline-lg font-headline text-primary leading-[1.1] tracking-tight mb-8">
                The Architect of <span className="text-tertiary">Economic Resilience</span>.
              </h1>
              <p className="text-lg text-on-surface-variant max-w-xl leading-relaxed">
                Beyond training, we are building a foundation for generational wealth. EITI bridges the gap between untapped human potential and the industries defining the 21st century.
              </p>
            </div>
            <div className="md:col-span-5 relative">
              <div className="aspect-[4/5] rounded-xl overflow-hidden editorial-shadow bg-surface-container-lowest p-2">
                <img
                  alt="Professional training environment"
                  className="w-full h-full object-cover rounded-xl"
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuAM0RRXx7rAZPrD5p0e1uY_Gt8cCGIbv3LPgeIiOBqyZg_-JXQymsizFBlRbhpENmEmrmFmC2v6XYEsJSmHtH2fA8EPnJ2VBbCayAjmFEPqqiR7IdDsgRUvePwP3tzz-Yy_kfGuXer9AZZw6po0On4FJHfmwCLaiU_vM28VJpZLJiwHH7uEJfrea5nwenGlIzbyJSKYIW2prowWKT3zcrVN4InWd4i8E5dArfeXfx9veTfJ1_txVApUPGeYAEtB1jEb0GA9FkUDvYny/"
                />
              </div>
              <div className="absolute -bottom-6 -left-6 bg-surface-container-lowest p-8 rounded-xl editorial-shadow max-w-[240px]">
                <p className="text-primary headline-lg font-headline font-black">12k+</p>
                <p className="text-sm font-semibold text-on-surface-variant">Careers Launched since 2018</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Impact Stats */}
      <section className="section-padding bg-surface-container-low">
        <div className="container-narrow">
          <div className="grid md:grid-cols-3 gap-16">
            <div className="space-y-4">
              <h3 className="text-on-surface-variant font-headline font-bold text-sm tracking-widest uppercase">Graduate Placement</h3>
              <div className="flex items-baseline gap-2">
                <span className="text-6xl font-headline font-extrabold text-primary">94%</span>
                <span className="material-symbols-outlined text-tertiary" data-weight="fill">trending_up</span>
              </div>
              <div className="h-1.5 w-full bg-surface-variant rounded-full overflow-hidden">
                <div className="h-full bg-primary" style={{ width: "94%" }}></div>
              </div>
              <p className="text-on-surface-variant text-sm leading-relaxed">Placement rate within 6 months of program completion across all sectors.</p>
            </div>
            <div className="space-y-4">
              <h3 className="text-on-surface-variant font-headline font-bold text-sm tracking-widest uppercase">Wage Increase</h3>
              <div className="flex items-baseline gap-2">
                <span className="text-6xl font-headline font-extrabold text-primary">2.4x</span>
              </div>
              <div className="h-1.5 w-full bg-surface-variant rounded-full overflow-hidden">
                <div className="h-full bg-tertiary" style={{ width: "70%" }}></div>
              </div>
              <p className="text-on-surface-variant text-sm leading-relaxed">Average increase in annual earnings compared to pre-enrollment status.</p>
            </div>
            <div className="space-y-4">
              <h3 className="text-on-surface-variant font-headline font-bold text-sm tracking-widest uppercase">Local Contribution</h3>
              <div className="flex items-baseline gap-2">
                <span className="text-6xl font-headline font-extrabold text-primary">$42M</span>
              </div>
              <div className="h-1.5 w-full bg-surface-variant rounded-full overflow-hidden">
                <div className="h-full bg-primary" style={{ width: "85%" }}></div>
              </div>
              <p className="text-on-surface-variant text-sm leading-relaxed">Estimated annual economic impact generated by our alumni in regional hubs.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Who We Serve & Opportunity Gap */}
      <section className="section-padding bg-surface">
        <div className="container-narrow">
          <div className="flex flex-col md:flex-row gap-20 items-start">
            <div className="md:w-1/3 sticky top-32">
              <h2 className="text-4xl font-headline font-extrabold text-primary mb-6">Bridging the <br />Opportunity Gap</h2>
              <p className="text-on-surface-variant leading-relaxed mb-8">
                The "Gap" isn't a lack of talent—it's a lack of access. We serve communities that have historically been sidelined from high-growth industrial sectors.
              </p>
              <div className="p-6 bg-tertiary-container text-on-tertiary-container rounded-xl">
                <p className="font-bold text-lg mb-2 italic">"Talent is universal; opportunity is not."</p>
              </div>
            </div>
            <div className="md:w-2/3 grid grid-cols-1 sm:grid-cols-2 gap-8">
              {/* Bento Grid of Needs */}
              <div className="bg-surface-container-lowest p-8 rounded-xl shadow-sm border-l-4 border-primary">
                <span className="material-symbols-outlined text-primary mb-4">groups</span>
                <h4 className="font-headline font-bold text-lg mb-2">Underemployed Adults</h4>
                <p className="text-sm text-on-surface-variant">Individuals working multiple part-time roles without benefits or stability.</p>
              </div>
              <div className="bg-surface-container-lowest p-8 rounded-xl shadow-sm border-l-4 border-tertiary">
                <span className="material-symbols-outlined text-tertiary mb-4">school</span>
                <h4 className="font-headline font-bold text-lg mb-2">First-Gen Professionals</h4>
                <p className="text-sm text-on-surface-variant">Students breaking through family cycles of low-wage manual labor.</p>
              </div>
              <div className="bg-surface-container-lowest p-8 rounded-xl shadow-sm border-l-4 border-primary">
                <span className="material-symbols-outlined text-primary mb-4">precision_manufacturing</span>
                <h4 className="font-headline font-bold text-lg mb-2">Displaced Workers</h4>
                <p className="text-sm text-on-surface-variant">Transitioning veteran labor from legacy industries to renewable tech.</p>
              </div>
              <div className="bg-surface-container-lowest p-8 rounded-xl shadow-sm border-l-4 border-tertiary">
                <span className="material-symbols-outlined text-tertiary mb-4">location_city</span>
                <h4 className="font-headline font-bold text-lg mb-2">Urban Youth</h4>
                <p className="text-sm text-on-surface-variant">Providing a direct pipeline from high school to high-paying trade careers.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Student Stories */}
      <section className="section-padding bg-primary text-on-primary">
        <div className="container-narrow">
          <div className="flex flex-col md:flex-row justify-between items-end mb-16 gap-6">
            <div>
              <h2 className="text-4xl md:text-5xl font-headline font-extrabold tracking-tight">Catalysts of Change</h2>
              <p className="text-on-primary-container mt-4 max-w-xl">Real stories from individuals who redefined their future through the EITI curriculum.</p>
            </div>
            <a className="flex items-center gap-2 group text-on-primary font-bold" href="#">
              View All Stories <span className="material-symbols-outlined group-hover:translate-x-1 transition-transform">arrow_forward</span>
            </a>
          </div>
          <div className="grid md:grid-cols-2 gap-12">
            <div className="flex flex-col md:flex-row gap-8 items-center bg-primary-container p-8 rounded-xl">
              <div className="w-full md:w-48 aspect-square rounded-xl overflow-hidden shrink-0">
                <img className="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDcJvJZZuMxW8lbQ6ogaZkoOBH-MEkYtQ7PSrXA1P-0DH0hX0a3ee879RP7lACdLF0jzNIUfw02_inoeQdd9SQsdVe2V8dNcmduz9lDCLXEiHeNn9rH8csW5x5mHp2hyrNHvLWyelefxVGmmc3sbHzDhsxGtFB7LqBhFjdnMt_q8GYZBpZOR387c8kQFVhi09dcADeW8W0yAvMq8HrMD7zuaidMRxrorTm-4avbVnixG0Z514SBiKWtRwm4x0fAQHe5Hf5kqlw-U_Fw" alt="Marcus T." />
              </div>
              <div>
                <span className="text-tertiary-fixed-dim font-bold text-xs tracking-widest uppercase">Fiber Optics Graduate</span>
                <h4 className="text-2xl font-headline font-bold mt-2 mb-4">Marcus T.</h4>
                <p className="text-on-primary-container text-sm leading-relaxed mb-6">"Before EITI, I was juggling three gig jobs just to make rent. Now, I'm a lead technician with a retirement plan and a clear path to management."</p>
                <div className="flex items-center gap-4 text-xs font-medium">
                  <span className="bg-white/10 px-3 py-1 rounded-full">New Salary: $68k</span>
                  <span className="bg-white/10 px-3 py-1 rounded-full">Previous: $22k</span>
                </div>
              </div>
            </div>
            <div className="flex flex-col md:flex-row gap-8 items-center bg-primary-container p-8 rounded-xl">
              <div className="w-full md:w-48 aspect-square rounded-xl overflow-hidden shrink-0">
                <img className="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDjaT_gaKvhiVLUuhRpIHe89brZGN6-r2FNeYikfpoWCNTvn3jkzFNMnjyU9qKaTOkfQNR1z6fyEzDEN0CqSMtj13VL9HX2lwf-S2hE2Hdzk8uRhUiToo5gFiPzZQbsygxOu3rvn_HkowYUsvypbeZ7eUgezQqYjbiRKSTFg1nVfaUvjwxels4OSicZ8Fajl4SQp0G-tDUgCcpRRcFV507YZDP5TeglAyEFpNe5nI24t1y2J5O1RvWSXghg0DJbjsUEHZmEDdkE-m__" alt="Sarah L." />
              </div>
              <div>
                <span className="text-tertiary-fixed-dim font-bold text-xs tracking-widest uppercase">Renewable Energy Specialist</span>
                <h4 className="text-2xl font-headline font-bold mt-2 mb-4">Sarah L.</h4>
                <p className="text-on-primary-container text-sm leading-relaxed mb-6">"Transitioning from retail to solar installation felt impossible until I found EITI. The hands-on training gave me the confidence to lead site assessments."</p>
                <div className="flex items-center gap-4 text-xs font-medium">
                  <span className="bg-white/10 px-3 py-1 rounded-full">New Salary: $74k</span>
                  <span className="bg-white/10 px-3 py-1 rounded-full">Previous: $31k</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Partners & Collaborations */}
      <section className="section-padding bg-surface">
        <div className="container-narrow">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-headline font-extrabold text-primary mb-4">Our Collaborative Ecosystem</h2>
            <p className="text-on-surface-variant max-w-2xl mx-auto">Impact is amplified through partnership. We work with industry giants and local governments to ensure our curriculum meets real-world demand.</p>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-12 items-center opacity-60">
            {["GLOBAL LOGISTICS", "CITY POWER & LIGHT", "TECH VENTURES", "URBAN RENEWAL"].map((name) => (
              <div key={name} className="flex justify-center grayscale hover:grayscale-0 transition-all duration-300 cursor-pointer group">
                <span className="text-xl font-headline font-black text-outline group-hover:text-primary transition-colors duration-300">{name}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Partner CTA */}
      <section className="section-padding bg-tertiary rounded-[2rem] mx-8 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-tertiary to-tertiary-container opacity-50"></div>
        <div className="relative z-10 container-narrow text-center">
          <h2 className="text-4xl md:text-5xl font-headline font-extrabold text-on-tertiary mb-8 leading-tight">Ready to co-author <br />the next success story?</h2>
          <p className="text-tertiary-fixed text-lg mb-12 max-w-2xl mx-auto leading-relaxed">
            Join our network of corporate partners, hiring managers, and donors to scale our impact to new regions.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="bg-on-tertiary text-tertiary px-10 py-4 rounded-xl font-headline font-extrabold text-lg hover:bg-tertiary-fixed transition-colors">
              Partner With Us
            </button>
            <button className="border-2 border-on-tertiary text-on-tertiary px-10 py-4 rounded-xl font-headline font-extrabold text-lg hover:bg-white/10 transition-colors">
              Download Impact Report
            </button>
          </div>
        </div>
      </section>
  </div>
);

export default ImpactPage;
